language: objective-c
xcode_workspace: Provenance.xcworkspace # path to your xcodeproj folder
xcode_scheme: Provenance-Release

language: objective-c
osx_image: xcode9.3

cache:
  directories:
  - Carthage
  - PVSupport/Carthage

# branches:
#   only:
#     - develop
#     - master
env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - WORKSPACE_NAME="Provenance.xcworkspace"
    - PROJECT_NAME="Provenance.xcodeproj"
    - SCHEME_IOS_FRAMEWORK="Provenance"
    - SCHEME_TVOS_FRAMEWORK="ProvenanceTV"
    - IOS_SDK=iphonesimulator11.3
    - TVOS_SDK=appletvsimulator11.3
  matrix:
    - DESTINATION="OS=11.3,name=iPhone X" SCHEME="$SCHEME_IOS_FRAMEWORK" SDK="$IOS_SDK"
    - DESTINATION="OS=11.3,name=Apple TV 1080p" SCHEME="$SCHEME_TVOS_FRAMEWORK" SDK="$TVOS_SDK"
before_install:
  # - gem install xcpretty -N
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
    - cd PVSupport
    - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
    - cd ..
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
script:
  - set -o pipefail
  - swiftlint
  - xcodebuild -workspace "$WORKSPACE_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
