language: objective-c
xcode_workspace: Provenance.xcworkspace # path to your xcodeproj folder
xcode_scheme: Provenance-Release

language: objective-c
osx_image: xcode9.2

# branches:
#   only:
#     - develop
#     - master
# env:
#   - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
# before_install:
#   - rvm install ruby-2.2.2
#   - gem install xcpretty -N
#   - brew update
#   - brew install swiftlint || true
# script:
#   - set -o pipefail
#   - xcodebuild -workspace Provenance.xcworkspace -scheme Provenance-Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
#   - swiftlint
